# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Conor

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Starting Selenium test'
  displayName: 'Starting Selenium'

- task: UseNode@1
  inputs:
    versionSpec: '18.12.0'
  displayName: 'Use Node.js'

- script: npm install selenium-webdriver
  displayName: 'Install Selenium WebDriver'

- script: |
    # Your Selenium test script (JavaScript)
    # This is a sample test checking if a view with a specific ID is displayed
    node Tests/selenium-tests.js
  displayName: 'Run Selenium Test'

